# Main file of the project
import find_images

# Generators
def generator(lyrics):
	generator_text(lyrics)


# download images for the lyrics
def generator_text(lyrics):
	setences = find_images.get_setences_from_lyrics(lyrics, nb_setences = 5)
	print(find_images.find_images(lyrics, nb_imgs=5))

# draw the shapes on the images 
def generator_shapes():
	pass



# Evaluators 
def evaluator():
	pass

# evaluate the images generated by the generator of images
def evaluator_text(setences):
	# numbers of setences
	# size of the images downloaded
	


	pass

# evaluate the shape generated by the drawing generator
def evaluator_shapes():
	# size of the shapes
	# shapes of the drawing
	# number of shapes 
	pass


# main 
def project():

	lyrics = "pink.txt"
	generator(lyrics)




project()